language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y
    - sudo apt-get update -qq

install:
    - sudo apt-get -y install intltool libwxbase3.0-dev libwxgtk3.0-dev

script:
  - ./autogen.sh
  - ./configure --prefix=/usr CPPFLAGS=-DNDEBUG
  - make -j$(nproc)
  - make install DESTDIR=$(readlink -f appdir) ; find appdir/
  - ( cd appdir/ ; find usr/ -type f -executable -exec sed -i -e "s|/usr|././|g" {} \; )
  - ( cd appdir/ ; sed -i 's/\.png//g' usr/share/applications/*.desktop )
  - rm appdir/usr/lib/libcsltools.la # No clue what this is or does
  - grep -r libcsltools.so.1 appdir/
  - find appdir/ ( -name '*.so*' -or '*.so' -or -executable ) -exec ldd {} \;
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ( cd appdir ; rm AppRun ; wget -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64" -O AppRun ; chmod a+x AppRun )
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./Cube*.AppImage https://transfer.sh/Cube*-git.$(git rev-parse --short HEAD)-x86_64.AppImage
