language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository 'deb http://repos.codelite.org/wx3.1.0/ubuntu/ trusty universe'
    - sudo apt-get update -qq
    
install:
    - sudo apt-get -y --allow-unauthenticated install intltool libwxbase3.1-dev libwxgtk3.1-dev

script:
  - ./autogen.sh
  - ./configure --prefix=/usr CPPFLAGS=-DNDEBUG
  - make -j$(nproc)
  - make install DESTDIR=$(readlink -f appdir) ; find appdir/
  - ( cd appdir/ ; find usr/ -type f -executable -exec sed -i -e "s|/usr|././|g" {} \; )
  - ( cd appdir/ ; sed -i 's/\.png//g' usr/share/applications/*.desktop ) # Dear upstream, please change this in desktop.in
  - ( cd appdir/usr/bin ; ln -s ../lib/csl/plugins/ . ) # Any idea why it searches in this weird place?
  - export LD_LIBRARY_PATH=appdir/usr/lib:appdir/usr/lib/csl:appdir/usr/lib/csl/plugins
  - FILES=$(find appdir/ -type f -name '*.so*' -or -name '*.so' -or -executable)
  - for FILE in $FILES; do echo $FILE; ldd $FILE; echo ===; done
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ( cd appdir ; rm AppRun ; wget -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64" -O AppRun ; chmod a+x AppRun )
  - ./linuxdeployqt*.AppImage --appimage-extract
  - squashfs-root/usr/bin/appimagetool ./appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./Cube*.AppImage https://transfer.sh/Cube_Server_Lister-git.$(git rev-parse --short HEAD)-x86_64.AppImage
